# Generated by Django 5.2.17 on 2026-09-27 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorBound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
            ],
            options={
                'verbose_name': 'граница цвета',
                'verbose_name_plural': 'границы цветов',
            },
        ),
        migrations.CreateModel(
            name='SurveySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_id', models.UUIDField(unique=True)),
                ('scale_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='версия шкалы')),
                ('blocks', models.JSONField(default=list, verbose_name='баллы блоков')),
            ],
            options={
                'verbose_name': 'снимок опроса',
                'verbose_name_plural': 'снимки опросов',
            },
        ),
    ]
