# Generated by Django 5.2.17 on 2026-09-27 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('survey', 'опрос'), ('review', 'ревью'), ('retro', 'ретро')], max_length=16, verbose_name='вид')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('collect', 'сбор'), ('review', 'разбор'), ('closed', 'закрыт')], default='draft', max_length=16, verbose_name='статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='дата и время')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыт в')),
                ('closed_by', models.UUIDField(blank=True, null=True, verbose_name='закрыл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'цикл',
                'verbose_name_plural': 'циклы',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamSurveySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.UUIDField(unique=True)),
                ('interval_months', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'интервал опроса',
                'verbose_name_plural': 'интервалы опросов',
            },
        ),
        migrations.CreateModel(
            name='CycleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='резюме')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='cycles.cycle')),
            ],
            options={
                'verbose_name': 'резюме цикла',
                'verbose_name_plural': 'резюме циклов',
            },
        ),
        migrations.CreateModel(
            name='RetroRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retro_record', to='cycles.cycle')),
            ],
            options={
                'verbose_name': 'запись ретро',
                'verbose_name_plural': 'записи ретро',
            },
        ),
        migrations.CreateModel(
            name='ReviewNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='cycles.cycle')),
            ],
            options={
                'verbose_name': 'заметки ревью',
                'verbose_name_plural': 'заметки ревью',
            },
        ),
    ]
