# Generated by Django 5.2.17 on 2026-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrorecord',
            name='artifacts',
            field=models.JSONField(blank=True, default=list, verbose_name='артефакты'),
        ),
        migrations.AddField(
            model_name='retrorecord',
            name='plan',
            field=models.TextField(blank=True, verbose_name='план'),
        ),
        migrations.AddField(
            model_name='reviewnotes',
            name='changes',
            field=models.TextField(blank=True, verbose_name='что изменяем'),
        ),
        migrations.AddField(
            model_name='reviewnotes',
            name='deviation_causes',
            field=models.TextField(blank=True, verbose_name='причины отклонений'),
        ),
        migrations.AddField(
            model_name='reviewnotes',
            name='plan_and_fact',
            field=models.TextField(blank=True, verbose_name='план и факт'),
        ),
        migrations.AddField(
            model_name='reviewnotes',
            name='reinforces',
            field=models.TextField(blank=True, verbose_name='что усиливаем'),
        ),
        migrations.AddField(
            model_name='reviewnotes',
            name='results',
            field=models.TextField(blank=True, verbose_name='результаты'),
        ),
        migrations.AddField(
            model_name='reviewnotes',
            name='stops',
            field=models.TextField(blank=True, verbose_name='что перестаём делать'),
        ),
    ]
