# Generated by Django 5.2.17 on 2026-09-27 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='teams.organization')),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.organization')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SelectedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='teams.team')),
            ],
            options={
                'verbose_name': 'выбранная команда',
                'verbose_name_plural': 'выбранные команды',
            },
        ),
        migrations.CreateModel(
            name='OrgLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='teams.organization')),
            ],
            options={
                'verbose_name': 'руководитель организации',
                'verbose_name_plural': 'руководители организаций',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'organization'), name='unique_org_leader')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('manager', 'менеджер'), ('leader', 'лидер'), ('member', 'участник'), ('facilitator', 'фасилитатор')], max_length=32, verbose_name='роль')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
            ],
            options={
                'verbose_name': 'участие',
                'verbose_name_plural': 'участия',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'team'), name='unique_team_membership')],
            },
        ),
    ]
