# Generated by Django 5.2.17 on 2026-09-27 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.UUIDField()),
                ('action', models.CharField(max_length=64, verbose_name='действие')),
                ('role', models.CharField(max_length=32, verbose_name='роль')),
            ],
            options={
                'verbose_name': 'право команды',
                'verbose_name_plural': 'права команды',
                'constraints': [models.UniqueConstraint(fields=('team_id', 'action', 'role'), name='unique_team_grant')],
            },
        ),
    ]
