# Generated by Django 5.2.17 on 2026-09-27 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.UUIDField()),
                ('text', models.TextField(verbose_name='текст')),
                ('source', models.CharField(choices=[('survey', 'опрос'), ('review', 'ревью'), ('manual', 'ручное опасение'), ('retro', 'ретроспектива')], max_length=16, verbose_name='источник')),
                ('for_discussion', models.BooleanField(default=False, verbose_name='к обсуждению')),
                ('status', models.CharField(choices=[('raised', 'поднята'), ('discussing', 'на обсуждении'), ('in_progress', 'в работе'), ('closed', 'закрыта')], default='raised', max_length=16, verbose_name='статус')),
                ('anonymous', models.BooleanField(default=False, verbose_name='анонимно')),
                ('author_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'проблема',
                'verbose_name_plural': 'проблемы',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField()),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='срок')),
                ('status', models.CharField(choices=[('assigned', 'назначено'), ('doing', 'делается'), ('done', 'сделано'), ('not_done', 'не сделано')], default='assigned', max_length=16, verbose_name='статус')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='problems.problem')),
            ],
            options={
                'verbose_name': 'действие',
                'verbose_name_plural': 'действия',
            },
        ),
        migrations.CreateModel(
            name='ProblemCycleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('raised', 'поднята в цикле'), ('carried', 'перенесена в цикл')], max_length=16, verbose_name='вид связи')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='problems.problem')),
            ],
            options={
                'verbose_name': 'связь проблемы с циклом',
                'verbose_name_plural': 'связи проблем с циклами',
                'constraints': [models.UniqueConstraint(fields=('problem', 'cycle_id', 'kind'), name='unique_problem_cycle_link')],
            },
        ),
    ]
