# Generated by Django 5.2.17 on 2026-09-27 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_kind', models.CharField(choices=[('problem', 'проблема'), ('action', 'действие'), ('cycle', 'цикл')], max_length=16)),
                ('target_id', models.UUIDField()),
                ('filename', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=64)),
                ('uploaded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
            },
        ),
        migrations.CreateModel(
            name='StatusAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=16)),
                ('object_id', models.UUIDField()),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('actor_id', models.UUIDField()),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'смена статуса',
                'verbose_name_plural': 'смены статусов',
                'ordering': ['at', 'id'],
            },
        ),
    ]
